# Generated by Django 3.2.4 on 2021-06-07 10:50

import assignment.models
import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson', to='forum.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('file', models.FileField(blank=True, null=True, upload_to=assignment.models.handle_upload_to)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 6, 7, 10, 50, 43, 377388))),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
