# Generated by Django 3.2.4 on 2021-06-07 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 6, 7, 11, 6, 7, 633154)),
        ),
    ]
